<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Syncfusion.Licensing" Version="*" />
		<PackageReference Include="Syncfusion.Maps.Windows" Version="*" />
		<PackageReference Include="Syncfusion.Shared.Base" Version="*" />
		<PackageReference Include="Syncfusion.Shared.Windows" Version="*" />
		<EmbeddedResource Include="world1.dbf">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="world1.shp">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>
</Project>